### ISSUE TITLE
Prazo de entrega

### ISSUE THREAD

**Issue by scorninpc** [cmacetko/APIs#1]
A jadlog não fornece prazo? to perguntando aqui, por que o suporte deles nao me responde, à 7 dias ja. Se puder ajudar com isso ae, agradeço

**Comment by cmacetko** [comment]
Não fornecem, porem eles tem uam API nova, a GetModal, que tem prazo

**Comment by scorninpc** [comment]
é, eu vi esse getmodal, mas não consegui acesso com nenhuma das informações que passaram. Suporte horrível. Mas obrigado, me deu a certeza que eu precisava, estava perdido

**Comment by cmacetko** [comment]
Sim, é complicado o suporte deles.
O que sigo sempre é:
O cliente solicita a unidade onde possui contrato a ativação do GetModal que é feito para o getmodal@riaworks.com.br, dae eles geram as credenciais
